### PR TITLE
Increase global scaling on DP-1 to 150%

### PR DESCRIPTION
**Pull request by burned42**
We got complaints that the font on our 4k monitors is hard to read because it's too small. Our FullHD monitors are all connected via VGA and the beamer is connected on DP-2 on the PC that is connected to the beamer, so just configuring a different scaling for DP-1 should work.

I'm not sure what would be a "good" scaling, but my assumption would be either 125% or 150%, I'm open to suggestions.

### CODE REVIEW

**Comment by burned42** [comment]
I heard about that and KDE also warned about that on the "in-between" scaling factors, but the warning is not there for scaling factors like 125/150/175/200%. To me it looked ok with this config on both, the FullHD screens as well as on the 4K screens, but as I never experienced the possible glitches with scaling, I also didn't know what to look for, so if you could double check, I'd highly appreciate.

**Comment by burned42** [comment]
> The settings didn't work for me.

It worked for me. Maybe we can take a look together at next Chaostreff.

**Comment by burned42** [comment]
We just tested this again and found that it didn't work with just this changeset. Additional files get changed when setting the scaling factor via GUI and unfortunately those files don't contain a scaling factor for each output individually but just one for all displays.

We had the idea that maybe at the time nixos writes the config files we could check which hardware we're running and only add the scaling adjustment in case we got one of the 4K displays attached.

@Hayajiro do you think something like this would be possible with some nixos magic?

**Comment by Hayajiro** [comment]
> do you think something like this would be possible with some nixos magic?

@burned42 Should be, might have a look next time.

**Comment by Hayajiro** [comment]
Basically, this can be handled by adding the following snippet to our existing [`system.activationScripts`](https://github.com/FabLab-Altmuehlfranken/NixOS-Workstation/blob/master/homedir.nix#L11-L18):

```bash
if [ -n "find /sys/devices -name 'modes' -path '*drm/card*' | grep 3840x2160" ];
then
    # UHD screen detected, applying scaling
    mv /home/fablab/.config/kde_uhd_patches/* /home/fablab/.config/
fi
```

The benefit of this specific solution is that it won't trigger if the screen doesn't support UHD but is connected via DP-1.

**Comment by burned42** [comment]
I moved the scaling adjustment to the activation script. Still needs to be tested though. I don't remember if on the presentation workstation both outputs are connected via DP, or if the beamer is connected via HDMI and ideally we don't want to scale the beamer as well I guess. I think we just need to test out what works best here.

**Comment by burned42** [comment]
IIRC we tested the current change set a while ago and it also didn't work as expected. As there were no other ideas on how to solve this, I'll close this PR for now.

**Pull request closed without merging**
